#!/bin/bash -e

cat /opt/downloads/cassandra-container.tar.gz | docker import - cassandra

# docker run --name=cassandra-server -d  -i -t --net=host --privileged=true --volume=/media/data/cassandra:/var/lib/cassandra cassandra /opt/cassandra/bin/cassandra -f

