#!/bin/bash -e

source /etc/environment

cat > /etc/systemd/system/etcd.service.d/30-onmetal.conf <<EOF
[Service]
Environment="ETCD_ADDR=${COREOS_PRIVATE_IPV4}:4001"
Environment="ETCD_PEER_ADDR=${COREOS_PRIVATE_IPV4}:7001"
EOF


systemctl daemon-reload

systemctl restart etcd.service
