#!/bin/bash -e

mkdir -p /media/data/cassandra-conf
mkdir -p /media/data/cassandra-log

cp -Rpv /opt/cassandra/opt/cassandra/conf/* /media/data/cassandra-conf/

/opt/bin/cassandra-config-file /media/data/cassandra-conf/cassandra.yaml

docker run -d \
 -i -t --net=host \
 --privileged=true \
 --volume=/media/data/cassandra-conf:/opt/cassandra/conf \
 --volume=/media/data/cassandra-log:/var/log/cassandra \
 --volume=/media/data/cassandra:/var/lib/cassandra \
 cassandra /opt/cassandra/bin/cassandra -f
